### PR TITLE
Improvements and fixes

### PR DESCRIPTION
**Pull request by andrewwoz**

### CODE REVIEW

**Comment by riko105** [comment]
Of course.

*By now penalty feature in test stage, but i'm trying to described in few words.
So, when players in certain match, score the same numbers of goals, penalty functions(or block) called. These piece of code executes ones for each match(when game in base & extra time is a TIE GAME ).*

1. PenaltyStage object is initializated with args(**Player*** homePlayer, **Player*** awayPlayer);
2.  function **getWinnerOfPenaltySeries:** called and calculate a winner 🙃
3. And then **KnockoutStage**'s property *winner* becomes a value of result of that function

I think it's pretty straightforward...

**Comment by andrewwoz** [comment]
Penalties is applied to knockout matches only. Isn't it?

**Comment by riko105** [comment]
I missed this, you're right 💯

**Comment by andrewwoz** [comment]
After 2 open issues will be fixed this branch will be merged.

**Comment by andrewwoz** [comment]
Last step needed. Testing.

**Comment by andrewwoz** [comment]
Tested. Works good.

**Pull request merged**
